In [1]:
%load_ext autoreload
# %autoreload 2

In [2]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np
import os

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)

logging.info(f"{os.getlogin()}| {datetime.now()}")

[02-08 09:19:38][INFO] David Andres| 2025-02-08 09:19:38.698553


In [69]:
# ####################################################################
def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``Ab``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab, dtype=float)
    assert Ab.shape[0] == Ab.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) < abs(Ab[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = Ab[i, :].copy()
            Ab[i, :] = Ab[p, :].copy()
            Ab[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i] / Ab[i, i]
            Ab[j, i:] = Ab[j, i:] - m * Ab[i, i:]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n)

    for i in range(n - 1, -1, -1):
        solucion[i] = Ab[i, -1] / Ab[i, i]

    return solucion

In [70]:
%autoreload 2
from src import matriz_aumentada

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b)
gauss_jordan(Ab)

[02-06 08:25:46][INFO] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-06 08:25:46][INFO] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-06 08:25:46][INFO] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[02-06 08:25:46][INFO] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [71]:
# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    # COMPLETAR
    # Debe basarse en la función gauss_jordan
    pass

## Ejemplos
* Ejemplo 1

In [72]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

* Ejemplo 2

In [73]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

## Ejercicios

* Ejercicio 1

In [74]:
A = [[2, -3], [-1, 1]]
inv_matrix(A)

* Ejercicio 2

In [75]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

* Ejercicio 3

In [76]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

* Ejercicio 4

In [77]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)

In [3]:
import numpy as np
import logging
logging.basicConfig(level=logging.INFO)

def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    
    Parameters:
        A: matriz cuadrada de tamaño n x n.
    
    Returns:
        A_inv: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    
    n = A.shape[0]
    assert A.shape[0] == A.shape[1], "La matriz debe ser cuadrada"
    
    print("Paso 0: Crear matriz aumentada [A|I]")
    aug = np.zeros((n, 2*n), dtype=float)
    aug[:, :n] = A
    aug[:, n:] = np.eye(n)
    print(aug)
    
    # Proceso de eliminación (Pasos 1-6)
    for i in range(n):
        print(f"\nPaso 1: i = {i}")
        
        # Paso 2: Encontrar pivote
        p = None
        for pi in range(i, n):
            if aug[pi, i] == 0:
                continue
            
            if p is None:
                p = pi
                continue
                
            if abs(aug[pi, i]) < abs(aug[p, i]):
                p = pi
        
        if p is None:
            raise ValueError("La matriz no es invertible")
            
        # Paso 3: Intercambiar filas si es necesario
        if p != i:
            print(f"Paso 3: Intercambiar filas {i} y {p}")
            aug[i, :], aug[p, :] = aug[p, :].copy(), aug[i, :].copy()
            print(aug)
        
        # Paso 4-6: Eliminación
        print(f"Paso 4-6: Eliminación para columna {i}")
        # Normalizar la fila del pivote
        aug[i, :] = aug[i, :] / aug[i, i]
        
        # Eliminar elemento en la columna actual de las otras filas
        for j in range(n):
            if i != j:
                m = aug[j, i]  # multiplicador
                print(f"m{j+1}{i+1} = {m:.4f}")
                aug[j, :] -= m * aug[i, :]
        print("Matriz después de eliminación:")
        print(aug)
    
    # Paso 7: Verificar solución única
    print("\nPaso 7: Verificar diagonal principal")
    for i in range(n):
        if abs(aug[i,i]) < 1e-10:
            raise ValueError("La matriz no es invertible")
    
    # La parte derecha de la matriz aumentada es la inversa
    print("\nPaso 8-10: Matriz inversa resultante:")
    A_inv = aug[:, n:]
    print(A_inv)
    
    return A_inv

# Ejercicio 1
print("\n=== Ejercicio 1 ===")
A1 = np.array([[2, -3], [-1, 1]])
print("Matriz original:")
print(A1)
inv1 = inv_matrix(A1)
print("\nVerificación (A * A^-1):")
print(np.dot(A1, inv1))

# Ejercicio 2
print("\n=== Ejercicio 2 ===")
A2 = np.array([
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0]
])
print("Matriz original:")
print(A2)
inv2 = inv_matrix(A2)
print("\nVerificación (A * A^-1):")
print(np.dot(A2, inv2))


=== Ejercicio 1 ===
Matriz original:
[[ 2 -3]
 [-1  1]]
Paso 0: Crear matriz aumentada [A|I]
[[ 2. -3.  1.  0.]
 [-1.  1.  0.  1.]]

Paso 1: i = 0
Paso 3: Intercambiar filas 0 y 1
[[-1.  1.  0.  1.]
 [ 2. -3.  1.  0.]]
Paso 4-6: Eliminación para columna 0
m21 = 2.0000
Matriz después de eliminación:
[[ 1. -1. -0. -1.]
 [ 0. -1.  1.  2.]]

Paso 1: i = 1
Paso 4-6: Eliminación para columna 1
m12 = -1.0000
Matriz después de eliminación:
[[ 1.  0. -1. -3.]
 [-0.  1. -1. -2.]]

Paso 7: Verificar diagonal principal

Paso 8-10: Matriz inversa resultante:
[[-1. -3.]
 [-1. -2.]]

Verificación (A * A^-1):
[[1. 0.]
 [0. 1.]]

=== Ejercicio 2 ===
Matriz original:
[[4 0 0 5]
 [1 0 4 0]
 [3 4 1 3]
 [1 3 3 0]]
Paso 0: Crear matriz aumentada [A|I]
[[4. 0. 0. 5. 1. 0. 0. 0.]
 [1. 0. 4. 0. 0. 1. 0. 0.]
 [3. 4. 1. 3. 0. 0. 1. 0.]
 [1. 3. 3. 0. 0. 0. 0. 1.]]

Paso 1: i = 0
Paso 3: Intercambiar filas 0 y 1
[[1. 0. 4. 0. 0. 1. 0. 0.]
 [4. 0. 0. 5. 1. 0. 0. 0.]
 [3. 4. 1. 3. 0. 0. 1. 0.]
 [1. 3. 3. 0. 0. 0. 0